nginx:
  hostname: nginx
  build: ./_nginx/
  links:
    - web:web
  ports:
    - 80:80

web:
  hostname: web
  build: ./web/
  links:
    - webdb:mysql
  privileged: true
  volumes:
    - ./volumes/web/wordpress:/opt/wordpress

webdb:
  hostname: webdb
  image: mysql:5.6
  environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    - MYSQL_ROOT_PASSWORD=wordpress
  privileged: true
  volumes:
    - ./volumes/web/mysql:/var/lib/mysql
